cask "docker"

brew "awscli"
brew "docker"
brew "docker-compose"
brew "python3"
brew 'jq'
brew 'jenv'
brew 'nvm'
brew 'git'
brew 'postgresql'
brew 'maven'

cask 'adoptopenjdk11'
cask 'intellij-idea-ce'
cask 'keystore-explorer'
cask 'alfred'
cask 'AppCleaner'
cask 'CheatSheet'
cask 'Firefox'
cask 'google-chrome'
cask 'LastPass'
cask 'megasync'
cask 'microsoft-office'
cask 'Postman'
cask 'ProtonVPN'
cask 'Spectacle'
cask 'sublime-text'
cask 'Todoist'
cask 'Vanilla'
cask 'veracrypt'
cask 'visual-studio-code'
cask 'vlc'







#Amphetamine
#Be Focused
#Encrypto
#Helium
#Keka
#LensOCR
