#! /usr/bin/env bash

# This install or updates homebrew before installing all the dependencies specified in the Brewfile.
# Keep in mind the homebrew does not keep track of versions so only the latest version is installed.

CURDIR=$(pwd)
ZSHRC_PATH="${HOME}/.zshrc"
LOCAL_ENV="${HOME}/.local.env"

install_brew_dependencies() {
    if ! which -s brew; then
        echo "Installing homebrew ..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    else
        echo "Looks like you already have homebrew. Updating ..."
        brew update
    fi

    echo "Installing development dependencies ..."

    if [[ ! -f "${CURDIR}/Brewfile" ]]; then
        cp "${CURDIR}/Brewfile.template" "${CURDIR}/Brewfile"
    fi

    brew tap adoptopenjdk/openjdk
    brew tap hashicorp/tap
    brew bundle
}

install_localenv_file() {
    if [[ ! -f "${LOCAL_ENV}" ]]; then
        touch ${LOCAL_ENV}
    fi
}

initialize_jenv() {
    install_localenv_file
    # Initialize JENV
    grep -qxf 'export PATH="$HOME/.jenv/bin:$PATH"' "${LOCAL_ENV}" || echo 'export PATH="$HOME/.jenv/bin:$PATH"' >>"${LOCAL_ENV}"
    grep -qxf 'eval "$(jenv init -)"' || echo 'eval "$(jenv init -)"' >>"${LOCAL_ENV}"
    jenv add $(/usr/libexec/java_home)
}

install_ohmyzsh() {
    if [[ ! -d "${HOME}/.oh-my-zsh" ]]; then
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
}

install_custom_plugin() {
    if [[ -d "${HOME}/.oh-my-zsh" ]]; then
        cp -R "${CURDIR}/zsh/plugins/local" "${HOME}/.oh-my-zsh/custom/plugins/"

        echo "Add \"local\" to your plugins in your ${ZSHRC_PATH}"
    else
        echo "Oh My Zsh must be installed first"
    fi
}

install_zsh-autosuggestions() {
    if [[ -d "${HOME}/.oh-my-zsh" ]]; then
        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-${HOME}/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

        echo "Add \"zsh-autosuggestions\" to your plugins in your ${ZSHRC_PATH}"
    else
        echo "Oh My Zsh must be installed first"
    fi
}

install_custom_themes() {
    if [[ -d "${HOME}/.oh-my-zsh" ]]; then
        cp -R "${CURDIR}/zsh/themes/" "${HOME}/.oh-my-zsh/custom/themes/"

        echo "You can change the theam in your ${ZSHRC_PATH}"
    else
        echo "Oh My Zsh must be installed first"
    fi
}

install_custom_fonts() {
    # clone
    git clone https://github.com/powerline/fonts.git --depth=1
    # install
    cd fonts
    ./install.sh
    # clean-up a bit
    cd ..
    rm -rf fonts
}

copy_zshrc_file() {
    cp -R "${CURDIR}/zsh/.zshrc" "${HOME}"
}

custom_zsh() {
    install_ohmyzsh
    install_custom_plugin
    install_zsh-autosuggestions
    install_custom_themes
    install_custom_fonts
    copy_zshrc_file
}

usage() {
    echo "setup command [OPTIONS]"
    echo -e "\nCommands:"
    echo "    b:      Installs the brew depedencies"
    echo "    zsh:    Installs the oh-my-zsh"
    echo "    czsh:   Installs the custom oh-my-zsh"
    echo "    all:    Installs all of the above"
    echo "    defaults:  Displays the current default values"
}

install_brew() {
    install_brew_dependencies
    initialize_jenv
}

SETUPCMD="${1}"

if [[ "${SETUPCMD}" != "defaults" ]]; then
    while [ $# -gt 0 ]; do
        if [[ $1 == *"--"* ]]; then
            param="${1/--/}"
            declare $param="$2"
        fi

        shift
    done
fi

case "${SETUPCMD}" in
defaults)
    echo "NVM Version:   ${nvm}"
    ;;
b)
    install_brew
    ;;
zsh)
    install_ohmyzsh
    ;;
czsh)
    custom_zsh
    ;;
com | all)
    install_brew
    install_ohmyzsh
    custom_zsh
    ;;
*)
    usage
    ;;
esac
